### ISSUE TITLE
[Proposal] Transform # access modifier due to tc39/proposal-private-fields

### ISSUE THREAD

**Issue by b12k** [tibdex/babel-plugin-transform-private-underscore#2]
First of all. Thank you for an awesome plugin!
IMHO You've created the best private plugin for babel so far.

Unfortunately I do not have enough babel plugin expertise so I want to make a proposal or a feature request, call it as you wish.
Can you modify your plugin to support tc39/proposal-private-fields?

Links:
1. https://tc39.github.io/proposal-private-fields
2. https://github.com/tc39/proposal-private-fields

Thank you in advance!

**Comment by tibdex** [comment]
Hi Bogdan,

If babel can parse identifiers starting with `#`, I guess it would be pretty easy to add a setting to the transform to accept `#` instead of `_`.

If I do so, I will need to change the repo and package name in order to keep it correct. "babel-plugin-transform-private-properties" or "babel-plugin-transform-private-fields" would be good fits but the first one is already taken and the second one might be too close to the proposal name and won't be really accurate since this plugin is broader than tc39/proposal-private-fields as it also can make methods private.

While tc39/proposal-private-fields requires to declare the private fields outside of the constructor, we don't need it currently. In fact, I have never tried the transform on a class with this kind of field declaration syntax. I will have to check to see if it works.

**Comment by tibdex** [comment]
Actually, babel's parser cannot parse the tc39/proposal-private-fields yet: https://astexplorer.net/#/SHyQuVDniq.

There is not much I can do in this repo until this new syntax is supported by babel.
You can subscribe to this ticket if you want updates on this: https://github.com/babel/babel/issues/4408.

**Comment by tibdex** [comment]
There is not a lot of activity on the TC39 proposal so I'm going to close this. Feel free to open another issue if the proposal get accepted.
